# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Klasha Store' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Klasha Store
  pod 'klashapay'

  target 'Klasha StoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Klasha StoreUITests' do
    # Pods for testing
  end

end
